//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelSQLData.VetSystemReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VetSystemReference.IOperateDatabase")]
    public interface IOperateDatabase {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperateDatabase/GetAllDoctors", ReplyAction="http://tempuri.org/IOperateDatabase/GetAllDoctorsResponse")]
        SOAPConnectToDatabase.Doctor[] GetAllDoctors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperateDatabase/GetAllDoctors", ReplyAction="http://tempuri.org/IOperateDatabase/GetAllDoctorsResponse")]
        System.Threading.Tasks.Task<SOAPConnectToDatabase.Doctor[]> GetAllDoctorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperateDatabase/InsertDoctor", ReplyAction="http://tempuri.org/IOperateDatabase/InsertDoctorResponse")]
        void InsertDoctor(SOAPConnectToDatabase.Doctor d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperateDatabase/InsertDoctor", ReplyAction="http://tempuri.org/IOperateDatabase/InsertDoctorResponse")]
        System.Threading.Tasks.Task InsertDoctorAsync(SOAPConnectToDatabase.Doctor d);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperateDatabaseChannel : ExcelSQLData.VetSystemReference.IOperateDatabase, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperateDatabaseClient : System.ServiceModel.ClientBase<ExcelSQLData.VetSystemReference.IOperateDatabase>, ExcelSQLData.VetSystemReference.IOperateDatabase {
        
        public OperateDatabaseClient() {
        }
        
        public OperateDatabaseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperateDatabaseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperateDatabaseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperateDatabaseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAPConnectToDatabase.Doctor[] GetAllDoctors() {
            return base.Channel.GetAllDoctors();
        }
        
        public System.Threading.Tasks.Task<SOAPConnectToDatabase.Doctor[]> GetAllDoctorsAsync() {
            return base.Channel.GetAllDoctorsAsync();
        }
        
        public void InsertDoctor(SOAPConnectToDatabase.Doctor d) {
            base.Channel.InsertDoctor(d);
        }
        
        public System.Threading.Tasks.Task InsertDoctorAsync(SOAPConnectToDatabase.Doctor d) {
            return base.Channel.InsertDoctorAsync(d);
        }
    }
}
